In [1]:
import numpy as np

In [2]:
def logistic(x):
    return (1.0 / (1.0 + np.exp(-x)))

In [3]:
# def GradientLogisticSurrogateLoss0(X, y):
#     n, d = X.shape
#     w0 = 0.
#     w = np.random.random(d)

#     g0 = 0.
#     g = np.zeros(d)
#     ps = w0
#     for i in range(n):
#         for j in range(d):
#             ps+=w[j] * X[i, j]
#         g0 += (logistic(y[i]*ps)-1.0)*y[i]
#         for j in range(d):
#             g[j] += (logistic(y[i]*ps)-1.0)*y[i]*X[i, j]
#     g/=n
#     return g
    

In [4]:
from sklearn.datasets import make_classification
X, y = make_classification(n_samples=100, n_features=10)

In [5]:
n, d = X.shape
w0 = 0.
w = np.random.random(d)

g0 = 0.
g = np.zeros(d)
ps = w0
for i in range(n):
    for j in range(d):
        ps+=w[j] * X[i, j]
    g0 += (logistic(y[i]*ps)-1.0)*y[i]
    for j in range(d):
        g[j] += (logistic(y[i]*ps)-1.0)*y[i]*X[i, j]
g/=n


In [6]:
g

array([ 0.10662097,  0.07604387,  0.04677539, -0.0520893 , -0.53722717,
       -0.03842213,  0.09648553, -0.04118927,  0.03814647,  0.26124687])

In [7]:
ps

-10.857930379149902

In [8]:
np.dot(w, X.T).sum()

-10.857930379149948

In [9]:
((logistic(y * ps) - 1.0)*y).sum()

-49.99903745200187

In [10]:
np.sum(list(map(lambda x: (logistic(x * ps)-1.0)*x, y)))

-49.99903745200187

In [11]:
test np.dot(y, ps)-1.0

SyntaxError: invalid syntax (<ipython-input-11-17ad5fc2cb67>, line 1)

In [12]:
(logistic(y)*ps - 1.0)

array([-8.93778315, -8.93778315, -8.93778315, -8.93778315, -8.93778315,
       -8.93778315, -6.42896519, -6.42896519, -8.93778315, -6.42896519,
       -8.93778315, -6.42896519, -8.93778315, -6.42896519, -8.93778315,
       -8.93778315, -8.93778315, -6.42896519, -6.42896519, -6.42896519,
       -6.42896519, -6.42896519, -8.93778315, -8.93778315, -8.93778315,
       -6.42896519, -6.42896519, -8.93778315, -6.42896519, -8.93778315,
       -8.93778315, -6.42896519, -8.93778315, -6.42896519, -6.42896519,
       -8.93778315, -8.93778315, -8.93778315, -6.42896519, -6.42896519,
       -6.42896519, -8.93778315, -6.42896519, -6.42896519, -8.93778315,
       -8.93778315, -6.42896519, -8.93778315, -6.42896519, -8.93778315,
       -6.42896519, -6.42896519, -6.42896519, -8.93778315, -8.93778315,
       -8.93778315, -8.93778315, -8.93778315, -8.93778315, -8.93778315,
       -6.42896519, -6.42896519, -6.42896519, -6.42896519, -6.42896519,
       -6.42896519, -8.93778315, -8.93778315, -8.93778315, -6.42

In [13]:
logistic(y[0]*ps)-1.0*y[0]

-0.9999807490400375

In [14]:
np.sum((logistic(y*ps)-1.0)*y)

-49.99903745200187

In [15]:
g0 = 0.
for i in range(n):
    g0 += (logistic(y[i]*ps)-1.0)*y[i]
print(g0)

-49.99903745200183


In [16]:
g0

-49.99903745200183

In [17]:
g = np.zeros(d)
for i in range(n):
    for j in range(d):
        g[j] += (logistic(y[i]*ps)-1.0)*y[i]*X[i, j]

In [18]:
g/n

array([ 0.1136041 ,  0.07665674,  0.03935434, -0.05335246, -0.54952494,
       -0.03964456,  0.09230523, -0.03624674,  0.03698542,  0.26658827])

In [19]:
(((logistic(y*ps) - 1.0)*y) @ X)/n

array([ 0.1136041 ,  0.07665674,  0.03935434, -0.05335246, -0.54952494,
       -0.03964456,  0.09230523, -0.03624674,  0.03698542,  0.26658827])

In [20]:
#TODO: Add weight vector as an argument to GradientLogisticSurrogateLoss and take into cosnideration the w0 case
#TODO: 
def GradientLogisticSurrogateLoss(X, y, w):
    """Computes the gradient logistic surrogate loss
    Parameters
    ----------
    
    X: {array like, sparse matrix}, shape (n_samples, n_features)
       Samples
    y: array, shape (n_samples)
       True labels
    w: array, shape (n_features)
       
    Returns
    -------
    Surrogate loss gradient vector
    """
    n, d = X.shape
    w0 = 0.
    g = np.zeros(d)
    ps = np.dot(w, X.T).sum()
    g0 = np.sum((logistic(y*ps)-1.0)*y)
    g += ((logistic(y*ps) - 1.0)*y) @ X
    g /= n
    return g, g0

In [21]:
w = np.random.random(X.shape[1])
g, g0 = GradientLogisticSurrogateLoss(X, y, w)

In [22]:
g0

-49.99958690630395

In [23]:
#TODO: A revoir!
def LogisticSurrogateLoss(X, y, w):
    """Computes the Logistic surrogate loss. Will be used for Logistic Regression
    Parameters
    ----------
    
    X: Array, shape (n_samples, n_features)
       Samples...
    y: array, shape (n_samples)
       True labels
    w: array shape (n_features,)
       Weight vector
       
    Returns
    -------
    Float, logistic SurrogateLoss value
    """
    n, d = X.shape
    ps = np.dot(w, X.T)
    S = (np.log(1.0 + np.exp(-y * ps))).sum()
    S /= n
    return S

In [24]:
w = np.random.random(X.shape[1])
Lold = LogisticSurrogateLoss(X, y, w)

In [25]:
n, d = X.shape

In [26]:
ps=np.dot(w, X.T)

In [27]:
ps

array([ 1.23482869e+00, -3.20039796e+00,  4.63824493e-01,  3.27129363e+00,
       -1.55908147e+00, -4.14920637e+00, -4.42205858e+00, -1.23031421e+00,
        6.95481074e-01, -6.65694718e+00, -2.22797456e+00, -2.20180147e+00,
       -5.70326212e-01,  5.88132165e-01,  1.69963729e+00,  1.17739070e+00,
        2.58147492e+00,  7.10446577e-01, -3.86996930e-01,  4.36250305e+00,
        1.47759233e-01, -2.25610677e+00, -2.34082976e+00, -5.54430289e-01,
       -1.98715166e+00, -2.52919875e+00,  2.41915225e+00,  2.23108214e+00,
        2.23924610e+00, -6.22688972e+00, -2.08294412e+00,  3.31005258e+00,
       -4.04078524e-01, -1.88445229e+00,  2.62547626e+00,  1.91901494e-01,
        9.23604093e-01,  3.31472886e-01, -6.76036614e-01,  2.31582258e+00,
        8.10631549e-01, -5.50227861e+00, -4.49801112e+00, -9.78367552e-01,
        1.67281715e+00, -6.48333563e+00,  2.37149933e+00,  5.07835940e+00,
       -1.66785162e+00,  3.16027051e+00, -8.76249329e-01, -3.03560908e+00,
       -2.20087759e+00,  

In [28]:
np.log(1.0 + np.exp(-y*ps)).sum() / n

1.0236582329815263

In [29]:
w

array([0.79128792, 0.82932286, 0.99046329, 0.10986741, 0.71671955,
       0.87780234, 0.54146582, 0.43204759, 0.86587738, 0.95199199])

# Line search

Before coding the conjugate gradient descent we have to code the line search which is used to optimize the learning step $\eta$

In [30]:
a = np.arange(11)
b = np.arange(11)

In [31]:
np.maximum(2,0)

2

In [32]:
#TODO: A quelle valeurs sont initialisées eta et eta2 ?
def line_search(X, y, w, cost_func, grd, wnew, Lold, g, g0, p, p0, L):
    """Computing line search algorithm
    Parameters
    -----------
    cost_func : function, 
            Cost function to minimize
    grd : function
        Gradient of cost function
    Lold : float,
        Vector of current loss 
    g : array 
        Vector of gradient
    p : array 
        Descent direction
    w : array 
        New weight vectors
    L: float 
        New loss value
    """
    print(L)
    _alpha = 1e-4
    _mineta = 1e-7
    m, d = X.shape
    pente = 0.
    # Computing the value of the slope
    pente = np.sum(p+g)
    
    # Defining minimal tolerated value of eta
    _max = 0.
    for j in range(d):
        print(np.abs(p[j]))
        print(np.abs(p[j]) > _max  * np.maximum(np.abs(w[0]), 1))
        if np.abs(p[j]) > _max  * np.maximum(np.abs(w[0]), 1):
            _max = np.maximum(np.abs(w[j]), 1.0)
    etamin = _mineta / _max
    
    ## Mise à jour du vecteur poids pour la plus grande valeur de eta
    ## à partir de laquelle on commence la recherche
    eta = 1.0
    wnew = w + (eta*p)
    
    L = cost_func(X, y, wnew)
    
    # Boucler tant que la condition d'Armijo n'est pas satisfaite (Eq. 2.18)
    while L > (Lold +_alpha*eta*pente):
        if eta < etamin:
            wnew = w
            break
        else:
            if eta == 1.0:
                etatmp = -pente/(2.0*(L-Lold-pente))
            else:
                coeff1 = L - Lold - eta*pente
                coeff2 = L - Lold - eta*pente
                # Calcul des coefficients du polynôme d'interpolation de degré 3 (Eq 2.33)
                a = (coeff1/(eta**2) - coeff2/(eta2**2)) / (eta-eta2)
                if a != 0.:
                    _delta = np.abs(((b**2)-3.0*a*pente).sum())
                    print("This is delta!")
                    print(_delta)
                    if _delta >= 0.:
                        # Le minimiseur du polynôme d'interpolationi de degré 3 (Eq. 2.34)
                        etatmp = ((-b+np.sqrt(_delta))/(3.*a)).sum()
                    else:
                        raise ValueError("rchln : problème d'interpolation")
                else:
                    etatmp = -pente/(2.0*b)
                    
                if etatmp > 0.5*eta:
                    etatmp = 0.5*eta
                    
        eta2 = eta
        L2 = L
        eta = np.maximum(etatmp, 0.1*eta)
        wnew = w + eta*p
        L = cost_func(X, y, wnew)

In [33]:
Lold

1.0236582329815263

In [34]:
w_new = np.random.random(X.shape[1])
Lold = LogisticSurrogateLoss(X, y, w_new)
p0, p = g0, g

line_search(X, y, w, LogisticSurrogateLoss, g, w, Lold, g, g0, p, p0, Lold)

0.9443807802857705
0.11360534351674163
True
0.07665757803728368
False
0.03935476796972177
False
0.05335304807304867
False
0.5495309774287122
False
0.03964499717721568
False
0.09230624935617487
False
0.036247136591752556
False
0.036985826057403054
False
0.2665911997507499
False
This is delta!
352.1461103960643
This is delta!
18583.534431925065
This is delta!
18169853.797094148
This is delta!
18090534055.19902
This is delta!
18082565256190.383
This is delta!
1.808176835073327e+16
This is delta!
1.8081688660274715e+19


In [35]:
_max = 0.
p[0] > _max  * np.maximum(np.abs(w[0]), 1)


True

In [36]:
def conjugate_gradient(X, y, w, cost_func, grd_func, eps=0.1):
    # Random initialization of weights
    m, d = X.shape
    w = np.random.random(d)
    
    # Initializing losses
    L = cost_func(X, y, w)
    Lold = L + 2*eps
    g, g0 = grd_func(X, y, w)
    p, p0 = -g, -g0
    t = 0
#     line_search(X, y, w, cost_func, g, w, Lold, g, g0, p, p0, L)
    while np.abs(Lold - L) > (np.abs(Lold) * eps):
        
       
        line_search(X, y, w, cost_func, g, w, Lold, g, g0, p, p0, L)
        # line search is supposed to modify the values of w ou initialiser.
        # creating new gradient vector h
#         h = np.gradient(cost_func(X, y, w))
        h, h0 = grd_func(X, y, w)
        dgg = np.linalg.norm(g)
        ngg = np.linalg.norm(h)
        beta = dgg / ngg # Formule de Fletcher-Reeves (Eq 2.53)
        wold = w
        g = h
        h0 = g0
        p = -g + beta*p # MAJ de la direction de descente (Eq 2.46)

In [37]:
conjugate_gradient(X, y, w, LogisticSurrogateLoss, GradientLogisticSurrogateLoss, )

0.7635150681477263
0.11349323467667986
True
0.07658193025620516
False
0.03931593161527394
False
0.053300397835409574
False
0.5489886853273864
False
0.03960587441669928
False
0.09221515904100633
False
0.03621136693239438
False
0.03694932743920723
False
0.26632812031056213
False
0.7635150681477263
0.22698646935335973
True
0.15316386051241032
False
0.07863186323054788
False
0.10660079567081915
False
1.0979773706547729
True
0.07921174883339856
False
0.18443031808201266
False
0.07242273386478876
False
0.07389865487841446
False
0.5326562406211243
False
0.7635150681477263
0.3404797040300396
True
0.22974579076861548
False
0.11794779484582182
False
0.15990119350622872
False
1.6469660559821593
True
0.11881762325009784
False
0.276645477123019
False
0.10863410079718314
False
0.11084798231762169
False
0.7989843609316865
False
0.7635150681477263
0.45397293870671945
True
0.30632772102482064
False
0.15726372646109577
False
0.2132015913416383
False
2.1959547413095457
True
0.15842349766679711
False
0.36

True
3.916628708555964
True
28.230780752919568
True
This is delta!
535.4737911388029
This is delta!
1120.1417799072456
This is delta!
7632.583048397585
0.7635150681477263
12.143776110404751
True
8.194266537413961
True
4.206804682834318
True
5.703142568388816
True
58.74178933003043
True
4.237828562586828
True
9.867022017387676
True
3.8746162617662043
True
3.953578035995171
True
28.49710887323013
True
This is delta!
550.1320888638331
This is delta!
1137.3402826508736
This is delta!
7709.861257799181
0.7635150681477263
12.257269345081431
True
8.270848467670167
True
4.246120614449592
True
5.756442966224225
True
59.290778015357816
True
4.277434437003527
True
9.959237176428681
True
3.910827628698599
True
3.9905273634343783
True
28.76343699354069
True
This is delta!
564.9118363393344
This is delta!
1154.662959141405
This is delta!
7787.658374799057
0.7635150681477263
12.370762579758111
True
8.347430397926372
True
4.285436546064866
True
5.809743364059634
True
59.8397667006852
True
4.3170403114

0.7635150681477263
22.69864693533588
True
15.316386051241064
True
7.863186323054802
True
10.66007956708187
True
109.79773706547745
True
7.921174883339829
True
18.443031808201248
True
7.242273386478889
True
7.389865487841441
True
53.26562406211232
True
This is delta!
2443.620416853861
This is delta!
3260.6736670998525
This is delta!
17057.28914305409
This is delta!
91724.93864043412
0.7635150681477263
22.812140170012558
True
15.39296798149727
True
7.902502254670076
True
10.71337996491728
True
110.34672575080484
True
7.960780757756528
True
18.535246967242255
True
7.278484753411283
True
7.426814815280649
True
53.531952182422884
True
This is delta!
2469.6783950764943
This is delta!
3289.0306472854504
This is delta!
17180.303177619302
This is delta!
92294.60306630295
0.7635150681477263
22.925633404689236
True
15.469549911753475
True
7.94181818628535
True
10.76668036275269
True
110.89571443613222
True
8.000386632173228
True
18.627462126283262
True
7.314696120343678
True
7.463764142719856
Tru

This is delta!
6161.825500047989
This is delta!
29505.387151769446
This is delta!
148324.1090233244
This is delta!
820216.2080150315
0.7635150681477263
32.68605158688358
True
22.055595913787
True
11.322988305198916
True
15.35051457659788
True
158.10874137428675
True
11.406491832009337
True
26.5579658038099
True
10.428873676529541
True
10.641406302491738
True
76.70249864944171
True
This is delta!
5200.549815390836
This is delta!
6200.265876314851
This is delta!
29668.912889718908
This is delta!
149057.0895659767
This is delta!
823791.8078003121
0.7635150681477263
32.79954482156026
True
22.132177844043202
True
11.36230423681419
True
15.403814974433288
True
158.65773005961412
True
11.446097706426036
True
26.650180962850907
True
10.465085043461935
True
10.678355629930946
True
76.96882676975227
True
This is delta!
5237.269900440672
This is delta!
6238.821829523858
This is delta!
29832.901905811483
This is delta!
149791.93523748053
This is delta!
827374.8019697953
0.7635150681477263
32.91303

True
19.9343487904432
True
205.32176831244084
True
14.812597031845446
True
34.488469481336445
True
13.543051232715388
True
13.819048462263634
True
99.60671699614997
True
This is delta!
8801.235801398812
This is delta!
9938.145852892145
This is delta!
45462.89433268096
This is delta!
219048.8371191517
This is delta!
1158875.0409919827
0.7635150681477263
42.55996300375489
True
28.718223846076715
True
14.743474355727756
True
19.98764918827861
True
205.8707569977682
True
14.852202906262145
True
34.58068464037745
True
13.579262599647782
True
13.855997789702842
True
99.87304511646053
True
This is delta!
8848.37352625794
This is delta!
9986.629521748826
This is delta!
45666.6490652187
This is delta!
219943.35285725998
This is delta!
1163091.8026464032
0.7635150681477263
42.67345623843157
True
28.794805776332918
True
14.78279028734303
True
20.04094958611402
True
206.41974568309558
True
14.891808780678844
True
34.67289979941845
True
13.615473966580176
True
13.89294711714205
True
100.13937323677

120.91296662099487
True
This is delta!
12955.013514536218
This is delta!
14181.211271086879
This is delta!
63221.85204766806
This is delta!
296450.00259383296
This is delta!
1519536.0291232164
This is delta!
8632089.117127707
0.7635150681477263
51.639421777889424
True
34.84477826657301
True
17.888748884949678
True
24.251681015111487
True
249.78985182395806
True
18.02067285959815
True
41.95789736365776
True
16.47617195423929
True
16.811943984839452
True
121.17929474130543
True
This is delta!
13011.841273726619
This is delta!
14238.918378313434
This is delta!
63462.52562290144
This is delta!
297492.29407132725
This is delta!
1524343.4624269204
This is delta!
8656520.571755894
0.7635150681477263
51.752915012566106
True
34.92136019682921
True
17.92806481656495
True
24.304981412946898
True
250.33884050928543
True
18.06027873401485
True
42.05011252269876
True
16.512383321171686
True
16.84889331227866
True
121.44562286161599
True
This is delta!
13068.79015549553
This is delta!
14296.740739856

19.04717900643936
True
19.4353462330231
True
140.08859128335527
True
This is delta!
17356.198600872427
This is delta!
18630.67462769885
This is delta!
81729.06033970734
This is delta!
376209.0658967636
This is delta!
1884567.91036809
This is delta!
10466234.896426667
0.7635150681477263
59.81093467461051
True
40.35867724501967
True
20.719495961249407
True
28.089309659261076
True
289.31703716753066
True
20.8722958176006
True
48.597388814610035
True
19.083390373371756
True
19.472295560462307
True
140.35491940366583
True
This is delta!
17421.74706744981
This is delta!
18696.67847323642
This is delta!
82002.93404217534
This is delta!
377384.12830805156
This is delta!
1889907.6329919249
This is delta!
10492779.764109574
0.7635150681477263
59.92442790928719
True
40.435259175275874
True
20.75881189286468
True
28.142610057096487
True
289.86602585285806
True
20.911901692017302
True
48.68960397365104
True
19.11960174030415
True
19.509244887901513
True
140.6212475239764
True
This is delta!
17487.4

This is delta!
12567018.67393994
0.7635150681477263
68.43642051003832
True
46.17890394449115
True
23.707506764010233
True
32.1401398947523
True
331.0401772524132
True
23.882342273269856
True
55.60574090172633
True
21.835454260233803
True
22.280444445841987
True
160.59585654726848
True
This is delta!
22757.824243890624
This is delta!
24050.05939423121
This is delta!
104166.05993007745
This is delta!
472081.72656410886
This is delta!
2317345.3009703835
This is delta!
12595785.963684298
0.7635150681477263
68.549913744715
True
46.25548587474735
True
23.746822695625507
True
32.19344029258771
True
331.5891659377406
True
23.921948147686557
True
55.69795606076733
True
21.871665627166198
True
22.317393773281193
True
160.86218466757904
True
This is delta!
22832.698836457057
This is delta!
24124.933668177
This is delta!
104475.42446855456
This is delta!
473398.69821700256
This is delta!
2323253.8135121604
This is delta!
12624582.472812137
0.7635150681477263
68.66340697939168
True
46.3320678050035

/home/iaamini/Documents/ML_practice/ML_fundamentals/virtualenv/lib/python3.6/site-packages/ipykernel_launcher.py:20: RuntimeWarning: overflow encountered in exp
/home/iaamini/Documents/ML_practice/ML_fundamentals/virtualenv/lib/python3.6/site-packages/ipykernel_launcher.py:57: RuntimeWarning: invalid value encountered in double_scalars


ValueError: rchln : problème d'interpolation

In [38]:
ps**2

array([1.52480188e+00, 1.02425471e+01, 2.15133161e-01, 1.07013620e+01,
       2.43073503e+00, 1.72159135e+01, 1.95546021e+01, 1.51367305e+00,
       4.83693924e-01, 4.43149458e+01, 4.96387063e+00, 4.84792972e+00,
       3.25271988e-01, 3.45899443e-01, 2.88876691e+00, 1.38624886e+00,
       6.66401277e+00, 5.04734339e-01, 1.49766624e-01, 1.90314329e+01,
       2.18327910e-02, 5.09001778e+00, 5.47948398e+00, 3.07392945e-01,
       3.94877172e+00, 6.39684630e+00, 5.85229759e+00, 4.97772750e+00,
       5.01422311e+00, 3.87741556e+01, 4.33865622e+00, 1.09564480e+01,
       1.63279453e-01, 3.55116045e+00, 6.89312559e+00, 3.68261833e-02,
       8.53044520e-01, 1.09874274e-01, 4.57025503e-01, 5.36303424e+00,
       6.57123508e-01, 3.02750699e+01, 2.02321041e+01, 9.57203067e-01,
       2.79831721e+00, 4.20336409e+01, 5.62400909e+00, 2.57897342e+01,
       2.78172902e+00, 9.98730968e+00, 7.67812886e-01, 9.21492248e+00,
       4.84386218e+00, 5.19891299e-06, 3.82684992e+01, 8.32086469e-01,
      

In [ ]:
def conjugate_gradient(X, y, cost_func, grd_func, epsilon=0.1):
    # Initialisation des poids w
    n, d = X.shape
    w = np.random.random(d)
    loss = cost_func(X, y, w)
    old_loss = loss
    p0 = grd_func(loss)
    t = 0
    while np.abs(loss - old_loss) <= epsilon * old_loss:
        eta = 