In [5]:
import numpy as np

In [6]:
def logistic(x):
    return (1.0 / (1.0 + np.exp(-x)))

In [142]:
def GradientLogisticSurrogateLoss0(X, y):
    n, d = X.shape
    w0 = 0.
    w = np.random.random(d)

    g0 = 0.
    g = np.zeros(d)
    ps = w0
    for i in range(n):
        for j in range(d):
            ps+=w[j] * X[i, j]
        g0 += (logistic(y[i]*ps)-1.0)*y[i]
        for j in range(d):
            g[j] += (logistic(y[i]*ps)-1.0)*y[i]*X[i, j]
    g/=n
    return g
    

In [143]:
from sklearn.datasets import make_classification
X, y = make_classification(n_samples=100, n_features=10)

In [144]:
GradientLogisticSurrogateLoss0(X, y)

array([ 0.03682867,  0.02101688,  0.02915964,  0.03551226, -0.069774  ,
       -0.01219663, -0.01050825,  0.00209623, -0.02498381, -0.01664432])

In [91]:
n, d = X.shape
w0 = 0.
w = np.random.random(d)

g0 = 0.
g = np.zeros(d)
ps = w0
for i in range(n):
    for j in range(d):
        ps+=w[j] * X[i, j]
    g0 += (logistic(y[i]*ps)-1.0)*y[i]
    for j in range(d):
        g[j] += (logistic(y[i]*ps)-1.0)*y[i]*X[i, j]
g/=n


In [92]:
g

array([-0.00254867,  0.01476864,  0.01523271,  0.00892982,  0.02342416,
        0.00858157, -0.04256896,  0.00468122,  0.00950882, -0.00435682])

In [27]:
ps

22.281618169632527

In [26]:
np.dot(w, X.T).sum()

22.281618169632537

In [30]:
((logistic(y * ps) - 1.0)*y).sum()

-1.073460853540098e-08

In [34]:
np.sum(list(map(lambda x: (logistic(x * ps)-1.0)*x, y)))

-1.073460853540098e-08

In [41]:
test np.dot(y, ps)-1.0

In [59]:
(logistic(y)*ps - 1.0)

-118.07262386747509

In [60]:
logistic(y[0]*ps)-1.0*y[0]

-0.8580230137836098

In [82]:
np.sum((logistic(y*ps)-1.0)*y)

-43.75917370296409

In [81]:
g0 = 0.
for i in range(n):
    g0 += (logistic(y[i]*ps)-1.0)*y[i]
print(g0)

-43.759173702964056


In [71]:
g0

-43.759173702964056

In [129]:
g = np.zeros(d)
for i in range(n):
    for j in range(d):
        g[j] += (logistic(y[i]*ps)-1.0)*y[i]*X[i, j]

In [130]:
g/n

array([ 1.12145268e-06, -1.11022231e-06,  2.47625631e-06,  1.31534448e-06,
        1.85367841e-06, -5.66040998e-07, -6.47950421e-06, -2.57208833e-08,
        1.03205161e-06, -9.27173845e-07])

In [117]:
(((logistic(y*ps) - 1.0)*y) @ X)/n

array([ 0.03338353, -0.03304923,  0.07371349,  0.03915533,  0.05518051,
       -0.01684997, -0.19288263, -0.00076566,  0.03072223, -0.02760022])

In [157]:
#TODO: Add weight vector as an argument to GradientLogisticSurrogateLoss and take into cosnideration the w0 case
#TODO: 
def GradientLogisticSurrogateLoss(X, y):
    """Computes the gradient logistic surrogate loss
    Parameters
    ----------
    
    X: {array like, sparse matrix}, shape (n_samples, n_features)
       Samples
    y: array, shape (n_samples)
       True labels
    w: array, shape (n_features)
       
    Returns
    -------
    Surrogate loss gradient vector
    """
    n, d = X.shape
    w0 = 0.
    w = np.random.random(d)
    g = np.zeros(d)
    ps = np.dot(w, X.T).sum()
    g0 = np.sum((logistic(y*ps)-1.0)*y)
    g += ((logistic(y*ps) - 1.0)*y) @ X
    g /= n
    return g

In [158]:
g

array([ 1.12145268e-04, -1.11022231e-04,  2.47625631e-04,  1.31534448e-04,
        1.85367841e-04, -5.66040998e-05, -6.47950421e-04, -2.57208833e-06,
        1.03205161e-04, -9.27173845e-05])

In [159]:
GradientSurrogateLoss(X, y)

array([-4.52737015e-07,  7.69958967e-07, -2.54075500e-06,  2.31380840e-06,
       -2.05979097e-05,  1.32437392e-06, -8.08784373e-06,  5.92098941e-06,
       -9.63457015e-07, -4.55798612e-06])

In [165]:
def LogisticSurrogateLoss(X, y, w):
    """Computes the Logistic surrogate loss. Will be used for Logistic Regression
    Parameters
    ----------
    
    X: Array, shape (n_samples, n_features)
       Samples...
    y: array, shape (n_samples)
       True labels
    w: array shape (n_features,)
       Weight vector
       
    Returns
    -------
    Float, logistic SurrogateLoss value
    """
    ps = np.dot(w, X.T).sum()
    S = (np.log(1.0 + np.exp(-y * ps))).sum()
    S /= n
    return S

In [166]:
w = np.random.random(X.shape[1])
LogisticSurrogateLoss(X, y, w)

0.541345760608077