In [1]:
import numpy as np

In [2]:
def logistic(x):
    return (1.0 / (1.0 + np.exp(-x)))

In [3]:
# def GradientLogisticSurrogateLoss0(X, y):
#     n, d = X.shape
#     w0 = 0.
#     w = np.random.random(d)

#     g0 = 0.
#     g = np.zeros(d)
#     ps = w0
#     for i in range(n):
#         for j in range(d):
#             ps+=w[j] * X[i, j]
#         g0 += (logistic(y[i]*ps)-1.0)*y[i]
#         for j in range(d):
#             g[j] += (logistic(y[i]*ps)-1.0)*y[i]*X[i, j]
#     g/=n
#     return g
    

In [4]:
from sklearn.datasets import make_classification
X, y = make_classification(n_samples=100, n_features=10)

In [5]:
n, d = X.shape
w0 = 0.
w = np.random.random(d)

g0 = 0.
g = np.zeros(d)
ps = w0
for i in range(n):
    for j in range(d):
        ps+=w[j] * X[i, j]
    g0 += (logistic(y[i]*ps)-1.0)*y[i]
    for j in range(d):
        g[j] += (logistic(y[i]*ps)-1.0)*y[i]*X[i, j]
g/=n


In [6]:
g

array([ 0.10662097,  0.07604387,  0.04677539, -0.0520893 , -0.53722717,
       -0.03842213,  0.09648553, -0.04118927,  0.03814647,  0.26124687])

In [7]:
ps

-10.857930379149902

In [8]:
np.dot(w, X.T).sum()

-10.857930379149948

In [9]:
((logistic(y * ps) - 1.0)*y).sum()

-49.99903745200187

In [10]:
np.sum(list(map(lambda x: (logistic(x * ps)-1.0)*x, y)))

-49.99903745200187

In [11]:
test np.dot(y, ps)-1.0

SyntaxError: invalid syntax (<ipython-input-11-17ad5fc2cb67>, line 1)

In [12]:
(logistic(y)*ps - 1.0)

array([-8.93778315, -8.93778315, -8.93778315, -8.93778315, -8.93778315,
       -8.93778315, -6.42896519, -6.42896519, -8.93778315, -6.42896519,
       -8.93778315, -6.42896519, -8.93778315, -6.42896519, -8.93778315,
       -8.93778315, -8.93778315, -6.42896519, -6.42896519, -6.42896519,
       -6.42896519, -6.42896519, -8.93778315, -8.93778315, -8.93778315,
       -6.42896519, -6.42896519, -8.93778315, -6.42896519, -8.93778315,
       -8.93778315, -6.42896519, -8.93778315, -6.42896519, -6.42896519,
       -8.93778315, -8.93778315, -8.93778315, -6.42896519, -6.42896519,
       -6.42896519, -8.93778315, -6.42896519, -6.42896519, -8.93778315,
       -8.93778315, -6.42896519, -8.93778315, -6.42896519, -8.93778315,
       -6.42896519, -6.42896519, -6.42896519, -8.93778315, -8.93778315,
       -8.93778315, -8.93778315, -8.93778315, -8.93778315, -8.93778315,
       -6.42896519, -6.42896519, -6.42896519, -6.42896519, -6.42896519,
       -6.42896519, -8.93778315, -8.93778315, -8.93778315, -6.42

In [13]:
logistic(y[0]*ps)-1.0*y[0]

-0.9999807490400375

In [14]:
np.sum((logistic(y*ps)-1.0)*y)

-49.99903745200187

In [15]:
g0 = 0.
for i in range(n):
    g0 += (logistic(y[i]*ps)-1.0)*y[i]
print(g0)

-49.99903745200183


In [16]:
g0

-49.99903745200183

In [17]:
g = np.zeros(d)
for i in range(n):
    for j in range(d):
        g[j] += (logistic(y[i]*ps)-1.0)*y[i]*X[i, j]

In [18]:
g/n

array([ 0.1136041 ,  0.07665674,  0.03935434, -0.05335246, -0.54952494,
       -0.03964456,  0.09230523, -0.03624674,  0.03698542,  0.26658827])

In [19]:
(((logistic(y*ps) - 1.0)*y) @ X)/n

array([ 0.1136041 ,  0.07665674,  0.03935434, -0.05335246, -0.54952494,
       -0.03964456,  0.09230523, -0.03624674,  0.03698542,  0.26658827])

In [20]:
#TODO: Add weight vector as an argument to GradientLogisticSurrogateLoss and take into cosnideration the w0 case
#TODO: 
def GradientLogisticSurrogateLoss(X, y, w):
    """Computes the gradient logistic surrogate loss
    Parameters
    ----------
    
    X: {array like, sparse matrix}, shape (n_samples, n_features)
       Samples
    y: array, shape (n_samples)
       True labels
    w: array, shape (n_features)
       
    Returns
    -------
    Surrogate loss gradient vector
    """
    n, d = X.shape
    w0 = 0.
    g = np.zeros(d)
    ps = np.dot(w, X.T).sum()
    g0 = np.sum((logistic(y*ps)-1.0)*y)
    g += ((logistic(y*ps) - 1.0)*y) @ X
    g /= n
    return g, g0

In [21]:
w = np.random.random(X.shape[1])
g, g0 = GradientLogisticSurrogateLoss(X, y, w)

In [22]:
g0

-49.99958690630395

In [23]:
#TODO: A revoir!
def LogisticSurrogateLoss(X, y, w):
    """Computes the Logistic surrogate loss. Will be used for Logistic Regression
    Parameters
    ----------
    
    X: Array, shape (n_samples, n_features)
       Samples...
    y: array, shape (n_samples)
       True labels
    w: array shape (n_features,)
       Weight vector
       
    Returns
    -------
    Float, logistic SurrogateLoss value
    """
    n, d = X.shape
    ps = np.dot(w, X.T)
    S = (np.log(1.0 + np.exp(-y * ps))).sum()
    S /= n
    return S

In [24]:
w = np.random.random(X.shape[1])
Lold = LogisticSurrogateLoss(X, y, w)

In [25]:
n, d = X.shape

In [26]:
ps=np.dot(w, X.T)

In [27]:
ps

array([ 1.23482869e+00, -3.20039796e+00,  4.63824493e-01,  3.27129363e+00,
       -1.55908147e+00, -4.14920637e+00, -4.42205858e+00, -1.23031421e+00,
        6.95481074e-01, -6.65694718e+00, -2.22797456e+00, -2.20180147e+00,
       -5.70326212e-01,  5.88132165e-01,  1.69963729e+00,  1.17739070e+00,
        2.58147492e+00,  7.10446577e-01, -3.86996930e-01,  4.36250305e+00,
        1.47759233e-01, -2.25610677e+00, -2.34082976e+00, -5.54430289e-01,
       -1.98715166e+00, -2.52919875e+00,  2.41915225e+00,  2.23108214e+00,
        2.23924610e+00, -6.22688972e+00, -2.08294412e+00,  3.31005258e+00,
       -4.04078524e-01, -1.88445229e+00,  2.62547626e+00,  1.91901494e-01,
        9.23604093e-01,  3.31472886e-01, -6.76036614e-01,  2.31582258e+00,
        8.10631549e-01, -5.50227861e+00, -4.49801112e+00, -9.78367552e-01,
        1.67281715e+00, -6.48333563e+00,  2.37149933e+00,  5.07835940e+00,
       -1.66785162e+00,  3.16027051e+00, -8.76249329e-01, -3.03560908e+00,
       -2.20087759e+00,  

In [28]:
np.log(1.0 + np.exp(-y*ps)).sum() / n

1.0236582329815263

In [29]:
w

array([0.79128792, 0.82932286, 0.99046329, 0.10986741, 0.71671955,
       0.87780234, 0.54146582, 0.43204759, 0.86587738, 0.95199199])

# Line search

Before coding the conjugate gradient descent we have to code the line search which is used to optimize the learning step $\eta$

In [30]:
a = np.arange(11)
b = np.arange(11)

In [31]:
np.maximum(2,0)

2

In [32]:
#TODO: A quelle valeurs sont initialisées eta et eta2 ?
def line_search(X, y, w, cost_func, grd, wnew, Lold, g, g0, p, p0, L):
    """Computing line search algorithm
    Parameters
    -----------
    cost_func : function, 
            Cost function to minimize
    grd : function
        Gradient of cost function
    Lold : float,
        Vector of current loss 
    g : array 
        Vector of gradient
    p : array 
        Descent direction
    w : array 
        New weight vectors
    L: float 
        New loss value
    """
    print(L)
    _alpha = 1e-4
    _mineta = 1e-7
    m, d = X.shape
    pente = 0.
    # Computing the value of the slope
    pente = np.sum(p+g)
    
    # Defining minimal tolerated value of eta
    _max = 0.
    for j in range(d):
        print(np.abs(p[j]))
        print(np.abs(p[j]) > _max  * np.maximum(np.abs(w[0]), 1))
        if np.abs(p[j]) > _max  * np.maximum(np.abs(w[0]), 1):
            _max = np.maximum(np.abs(w[j]), 1.0)
    etamin = _mineta / _max
    
    ## Mise à jour du vecteur poids pour la plus grande valeur de eta
    ## à partir de laquelle on commence la recherche
    eta = 1.0
    wnew = w + (eta*p)
    
    L = cost_func(X, y, wnew)
    
    # Boucler tant que la condition d'Armijo n'est pas satisfaite (Eq. 2.18)
    while L > (Lold +_alpha*eta*pente):
        if eta < etamin:
            wnew = w
            break
        else:
            if eta == 1.0:
                etatmp = -pente/(2.0*(L-Lold-pente))
            else:
                coeff1 = L - Lold - eta*pente
                coeff2 = L - Lold - eta*pente
                # Calcul des coefficients du polynôme d'interpolation de degré 3 (Eq 2.33)
                a = (coeff1/(eta**2) - coeff2/(eta2**2)) / (eta-eta2)
                if a != 0.:
                    _delta = np.abs(((b**2)-3.0*a*pente).sum())
                    print("This is delta!")
                    print(_delta)
                    if _delta >= 0.:
                        # Le minimiseur du polynôme d'interpolationi de degré 3 (Eq. 2.34)
                        etatmp = ((-b+np.sqrt(_delta))/(3.*a)).sum()
                    else:
                        raise ValueError("rchln : problème d'interpolation")
                else:
                    etatmp = -pente/(2.0*b)
                    
                if etatmp > 0.5*eta:
                    etatmp = 0.5*eta
                    
        eta2 = eta
        L2 = L
        eta = np.maximum(etatmp, 0.1*eta)
        wnew = w + eta*p
        L = cost_func(X, y, wnew)

In [33]:
Lold

1.0236582329815263

In [34]:
w_new = np.random.random(X.shape[1])
Lold = LogisticSurrogateLoss(X, y, w_new)
p0, p = g0, g

line_search(X, y, w, LogisticSurrogateLoss, g, w, Lold, g, g0, p, p0, Lold)

0.9443807802857705
0.11360534351674163
True
0.07665757803728368
False
0.03935476796972177
False
0.05335304807304867
False
0.5495309774287122
False
0.03964499717721568
False
0.09230624935617487
False
0.036247136591752556
False
0.036985826057403054
False
0.2665911997507499
False
This is delta!
352.1461103960643
This is delta!
18583.534431925065
This is delta!
18169853.797094148
This is delta!
18090534055.19902
This is delta!
18082565256190.383
This is delta!
1.808176835073327e+16
This is delta!
1.8081688660274715e+19


In [35]:
_max = 0.
p[0] > _max  * np.maximum(np.abs(w[0]), 1)


True

In [36]:
def conjugate_gradient(X, y, w, cost_func, grd_func, eps=0.1):
    # Random initialization of weights
    m, d = X.shape
    w = np.random.random(d)
    
    # Initializing losses
    L = cost_func(X, y, w)
    Lold = L + 2*eps
    g, g0 = grd_func(X, y, w)
    p, p0 = -g, -g0
    t = 0
#     line_search(X, y, w, cost_func, g, w, Lold, g, g0, p, p0, L)
    while np.abs(Lold - L) > (np.abs(Lold) * eps):
        
       
        line_search(X, y, w, cost_func, g, w, Lold, g, g0, p, p0, L)
        # line search is supposed to modify the values of w ou initialiser.
        # creating new gradient vector h
#         h = np.gradient(cost_func(X, y, w))
        h, h0 = grd_func(X, y, w)
        dgg = np.linalg.norm(g)
        ngg = np.linalg.norm(h)
        beta = dgg / ngg # Formule de Fletcher-Reeves (Eq 2.53)
        wold = w
        g = h
        h0 = g0
        p = -g + beta*p # MAJ de la direction de descente (Eq 2.46)

In [1]:
# conjugate_gradient(X, y, w, LogisticSurrogateLoss, GradientLogisticSurrogateLoss, )

In [38]:
ps**2

array([1.52480188e+00, 1.02425471e+01, 2.15133161e-01, 1.07013620e+01,
       2.43073503e+00, 1.72159135e+01, 1.95546021e+01, 1.51367305e+00,
       4.83693924e-01, 4.43149458e+01, 4.96387063e+00, 4.84792972e+00,
       3.25271988e-01, 3.45899443e-01, 2.88876691e+00, 1.38624886e+00,
       6.66401277e+00, 5.04734339e-01, 1.49766624e-01, 1.90314329e+01,
       2.18327910e-02, 5.09001778e+00, 5.47948398e+00, 3.07392945e-01,
       3.94877172e+00, 6.39684630e+00, 5.85229759e+00, 4.97772750e+00,
       5.01422311e+00, 3.87741556e+01, 4.33865622e+00, 1.09564480e+01,
       1.63279453e-01, 3.55116045e+00, 6.89312559e+00, 3.68261833e-02,
       8.53044520e-01, 1.09874274e-01, 4.57025503e-01, 5.36303424e+00,
       6.57123508e-01, 3.02750699e+01, 2.02321041e+01, 9.57203067e-01,
       2.79831721e+00, 4.20336409e+01, 5.62400909e+00, 2.57897342e+01,
       2.78172902e+00, 9.98730968e+00, 7.67812886e-01, 9.21492248e+00,
       4.84386218e+00, 5.19891299e-06, 3.82684992e+01, 8.32086469e-01,
      

In [ ]:
def conjugate_gradient(X, y, cost_func, grd_func, epsilon=0.1):
    # Initialisation des poids w
    n, d = X.shape
    w = np.random.random(d)
    loss = cost_func(X, y, w)
    old_loss = loss
    p0 = grd_func(loss)
    t = 0
    while np.abs(loss - old_loss) <= epsilon * old_loss:
        eta = 